# Generated by Django 5.1.15 on 2026-05-01 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcasts', '0002_segment_adminmessagelog_buttons_payload_and_more'),
        ('users', '0002_pushtopic_tag_useradminstate_admin_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('rating', 'Rating'), ('nps', 'NPS'), ('single_choice', 'Single Choice'), ('text', 'Text')], default='rating', max_length=32)),
                ('options', models.JSONField(blank=True, default=list)),
                ('target_type', models.CharField(choices=[('all', 'All'), ('segment', 'Segment'), ('tag', 'Tag'), ('manual_users', 'Manual Users'), ('push_topic', 'Push Topic')], default='all', max_length=32)),
                ('manual_users', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('low_rating_threshold', models.PositiveIntegerField(default=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_campaigns', to=settings.AUTH_USER_MODEL)),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_campaigns', to='broadcasts.segment')),
                ('target_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_campaigns', to='users.tag')),
                ('target_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_campaigns', to='users.pushtopic')),
            ],
            options={
                'verbose_name': 'Poll Campaign',
                'verbose_name_plural': 'Poll Campaigns',
                'db_table': 'poll_campaigns',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PollRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('responded', 'Responded')], default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='polls.pollcampaign')),
                ('user', models.ForeignKey(db_column='telegram_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='poll_recipients', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Poll Recipient',
                'verbose_name_plural': 'Poll Recipients',
                'db_table': 'poll_recipients',
                'ordering': ('id',),
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='')),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, default='')),
                ('telegram_poll_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.pollcampaign')),
                ('user', models.ForeignKey(db_column='telegram_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Poll Response',
                'verbose_name_plural': 'Poll Responses',
                'db_table': 'poll_responses',
                'ordering': ('-created_at',),
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
