# Generated by Django 5.1.15 on 2026-05-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        ('users', '0002_pushtopic_tag_useradminstate_admin_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('transaction_flow', 'Transaction Flow'), ('subscription', 'Subscription'), ('poll', 'Poll'), ('manual', 'Manual'), ('support', 'Support')], default='manual', max_length=32)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('ux', 'UX'), ('feature_request', 'Feature Request'), ('payment', 'Payment'), ('recognition', 'Recognition'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('planned', 'Planned'), ('rejected', 'Rejected'), ('converted_to_case', 'Converted to Case')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='support.supportcase')),
                ('tags', models.ManyToManyField(blank=True, related_name='feedback_items', to='users.tag')),
                ('user', models.ForeignKey(blank=True, db_column='telegram_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback_items',
                'ordering': ('-created_at',),
            },
        ),
    ]
