# Generated by Django 5.1.15 on 2026-09-22 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import miniapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0008_install_nudge_device_state'),
        ('users', '0012_useroidctokenuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Назва')),
                ('code', models.CharField(default=miniapp.models.generate_partner_link_code, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Використовуйте 3–64 малих латинських літери, цифри, _ або -.', regex='^[a-z0-9][a-z0-9_-]{2,63}$')], verbose_name='Код посилання')),
                ('destination', models.CharField(choices=[('landing', 'Лендінг'), ('app', 'Вебзастосунок')], default='landing', max_length=16, verbose_name='Куди вести')),
                ('utm_source', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Використовуйте лише латинські літери, цифри, крапку, _ або -.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')], verbose_name='Джерело (utm_source)')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=128, validators=[django.core.validators.RegexValidator(message='Використовуйте лише латинські літери, цифри, крапку, _ або -.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')], verbose_name='Канал (utm_medium)')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=128, validators=[django.core.validators.RegexValidator(message='Використовуйте лише латинські літери, цифри, крапку, _ або -.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')], verbose_name='Кампанія (utm_campaign)')),
                ('utm_content', models.CharField(blank=True, default='', max_length=128, validators=[django.core.validators.RegexValidator(message='Використовуйте лише латинські літери, цифри, крапку, _ або -.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')], verbose_name='Креатив (utm_content)')),
                ('utm_term', models.CharField(blank=True, default='', max_length=128, validators=[django.core.validators.RegexValidator(message='Використовуйте лише латинські літери, цифри, крапку, _ або -.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')], verbose_name='Ключ / сегмент (utm_term)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Нотатки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'партнерське посилання',
                'verbose_name_plural': 'партнерські посилання',
                'db_table': 'partner_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PartnerLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'partner_link_clicks',
                'ordering': ('-clicked_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='acquisitionsession',
            name='last_partner_link_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisitionsession',
            name='first_partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_touch_sessions', to='miniapp.partnerlink'),
        ),
        migrations.AddField(
            model_name='acquisitionsession',
            name='last_partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_touch_sessions', to='miniapp.partnerlink'),
        ),
        migrations.AddField(
            model_name='funnelevent',
            name='first_partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_touch_events', to='miniapp.partnerlink'),
        ),
        migrations.AddField(
            model_name='funnelevent',
            name='last_partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_touch_events', to='miniapp.partnerlink'),
        ),
        migrations.AddIndex(
            model_name='acquisitionsession',
            index=models.Index(fields=['first_partner_link', 'created_at'], name='acq_first_link_time_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitionsession',
            index=models.Index(fields=['last_partner_link', 'created_at'], name='acq_last_link_time_idx'),
        ),
        migrations.AddField(
            model_name='partnerlinkclick',
            name='acquisition_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_link_clicks', to='miniapp.acquisitionsession'),
        ),
        migrations.AddField(
            model_name='partnerlinkclick',
            name='partner_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clicks', to='miniapp.partnerlink'),
        ),
        migrations.AddIndex(
            model_name='partnerlinkclick',
            index=models.Index(fields=['partner_link', 'clicked_at'], name='partner_click_link_time_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerlinkclick',
            index=models.Index(fields=['acquisition_session', 'clicked_at'], name='partner_click_sess_time_idx'),
        ),
        migrations.AddIndex(
            model_name='funnelevent',
            index=models.Index(fields=['first_partner_link', 'event_name', 'recorded_at'], name='funnel_first_link_event_idx'),
        ),
        migrations.AddIndex(
            model_name='funnelevent',
            index=models.Index(fields=['last_partner_link', 'event_name', 'recorded_at'], name='funnel_last_link_event_idx'),
        ),
    ]
