# Generated by Django 5.1.15 on 2026-09-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0009_partnerlink_partnerlinkclick_and_more'),
    ]

    # The final, not-yet-deployed 0009 migration already contains these fields
    # and indexes. Keep this generated migration as a no-op so existing local
    # migration references remain valid without applying duplicate DDL.
    operations = []
