"""Versioned core-only DDL extracted from bot_main.init_db, not legacy SQL.

Do not put Django-managed tables, seed data, or finance backfills here.
Preserve historical statements; append explicit idempotent schema upgrades.
"""

CORE_TABLES = ('users', 'families', 'family_members', 'family_invites', 'accounts', 'category_templates', 'categories', 'transactions', 'ai_transaction_drafts', 'saving_prompt_settings', 'pending_saving_tasks', 'daily_expense_reminder_settings', 'daily_expense_day_statuses', 'debts', 'debt_payments', 'debt_invites')

CORE_STATEMENTS = (
    'CREATE TABLE IF NOT EXISTS users (\n  tg_user_id BIGINT PRIMARY KEY,\n  first_name TEXT,\n  last_name TEXT,\n  username TEXT,\n  lang TEXT,\n  base_currency TEXT,\n  start_date DATE,\n  onboarding_completed BOOLEAN NOT NULL DEFAULT false,\n  onboarding_version INT NOT NULL DEFAULT 0,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS start_date DATE',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT false',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_version INT NOT NULL DEFAULT 0',
    "CREATE TABLE IF NOT EXISTS families (\n  id BIGSERIAL PRIMARY KEY,\n  name VARCHAR(255) NOT NULL,\n  owner_user_id BIGINT NOT NULL REFERENCES users (tg_user_id),\n  status VARCHAR(32) NOT NULL DEFAULT 'active',\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)",
    "CREATE TABLE IF NOT EXISTS family_members (\n  id BIGSERIAL PRIMARY KEY,\n  family_id BIGINT NOT NULL REFERENCES families (id),\n  user_id BIGINT NOT NULL REFERENCES users (tg_user_id),\n  role VARCHAR(32) NOT NULL,\n  status VARCHAR(32) NOT NULL DEFAULT 'active',\n  invited_by_user_id BIGINT NULL REFERENCES users (tg_user_id),\n  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  removed_at TIMESTAMPTZ NULL,\n  left_at TIMESTAMPTZ NULL,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  UNIQUE (family_id, user_id)\n)",
    "CREATE TABLE IF NOT EXISTS family_invites (\n  id BIGSERIAL PRIMARY KEY,\n  family_id BIGINT NOT NULL REFERENCES families (id),\n  created_by_user_id BIGINT NOT NULL REFERENCES users (tg_user_id),\n  token_hash VARCHAR(255) NOT NULL UNIQUE,\n  status VARCHAR(32) NOT NULL DEFAULT 'active',\n  max_uses INT NOT NULL DEFAULT 1,\n  used_count INT NOT NULL DEFAULT 0,\n  expires_at TIMESTAMPTZ NOT NULL,\n  used_at TIMESTAMPTZ NULL,\n  used_by_user_id BIGINT NULL REFERENCES users (tg_user_id),\n  revoked_at TIMESTAMPTZ NULL,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)",
    'CREATE INDEX IF NOT EXISTS idx_family_members_user_active ON family_members (user_id, status)',
    'CREATE INDEX IF NOT EXISTS idx_family_invites_family_active ON family_invites (family_id, status)',
    "CREATE TABLE IF NOT EXISTS accounts (\n  id BIGSERIAL PRIMARY KEY,\n  tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  label TEXT NOT NULL,\n  currency TEXT NOT NULL,\n  account_type TEXT NOT NULL DEFAULT 'other',\n  starting_balance NUMERIC NOT NULL DEFAULT 0,\n  balance NUMERIC(18,2) NOT NULL DEFAULT 0,\n  credit_limit NUMERIC(18,2),\n  monthly_interest_rate NUMERIC,\n  non_negative_account_type TEXT NOT NULL DEFAULT 'main',\n  is_active BOOLEAN NOT NULL DEFAULT true,\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)",
    "ALTER TABLE accounts ADD COLUMN IF NOT EXISTS account_type TEXT NOT NULL DEFAULT 'other'",
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS balance NUMERIC(18,2) NOT NULL DEFAULT 0',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(18,2)',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS monthly_interest_rate NUMERIC',
    "ALTER TABLE accounts ADD COLUMN IF NOT EXISTS non_negative_account_type TEXT NOT NULL DEFAULT 'main'",
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS goal_name TEXT',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS goal_amount NUMERIC(18,2)',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS goal_date DATE',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS family_id BIGINT NULL REFERENCES families (id)',
    'ALTER TABLE accounts ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT NULL REFERENCES users (tg_user_id)',
    'CREATE TABLE IF NOT EXISTS category_templates (\n  id BIGSERIAL PRIMARY KEY,\n  type TEXT NOT NULL,\n  name TEXT NOT NULL,\n  slug TEXT NULL,\n  aliases TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],\n  sort_order INT NOT NULL DEFAULT 0,\n  is_system BOOLEAN NOT NULL DEFAULT false,\n  is_active BOOLEAN NOT NULL DEFAULT true,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ux_category_templates_type_name ON category_templates (type, name)',
    'ALTER TABLE category_templates ADD COLUMN IF NOT EXISTS slug TEXT',
    'CREATE UNIQUE INDEX IF NOT EXISTS ux_category_templates_type_slug ON category_templates (type, slug) WHERE slug IS NOT NULL',
    'CREATE TABLE IF NOT EXISTS categories (\n  id BIGSERIAL PRIMARY KEY,\n  tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  kind TEXT NOT NULL,\n  name TEXT NOT NULL,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)',

    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS user_id BIGINT',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS template_id BIGINT',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS type TEXT',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS slug TEXT',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS aliases TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[]',
    "ALTER TABLE categories ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'legacy'",
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT false',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ NULL',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS family_id BIGINT NULL REFERENCES families (id)',
    'ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT NULL REFERENCES users (tg_user_id)',
    'DROP INDEX IF EXISTS idx_categories_unique',
    "WITH ranked AS (SELECT id, ROW_NUMBER() OVER (PARTITION BY family_id, kind, name ORDER BY id) AS rn FROM categories WHERE family_id IS NOT NULL AND is_active) UPDATE categories c SET is_active=false, deleted_at=COALESCE(c.deleted_at, now()), updated_at=now() FROM ranked r WHERE c.id=r.id AND r.rn>1",
    'CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_personal_active ON categories (tg_user_id, kind, name) WHERE family_id IS NULL AND is_active',
    'CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_family_active ON categories (family_id, kind, name) WHERE family_id IS NOT NULL AND is_active',
    'CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_user_type_slug ON categories (user_id, type, slug) WHERE family_id IS NULL AND slug IS NOT NULL',
    'CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_family_type_slug ON categories (family_id, type, slug) WHERE family_id IS NOT NULL AND slug IS NOT NULL',
    "CREATE TABLE IF NOT EXISTS transactions (\n    id BIGSERIAL PRIMARY KEY,\n    tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  date DATE NOT NULL,\n  type TEXT NOT NULL,\n  amount NUMERIC NOT NULL,\n  currency TEXT NOT NULL,\n  to_amount NUMERIC,\n  to_currency TEXT,\n  fx_rate NUMERIC,\n  fx_rate_text TEXT,\n  comment TEXT,\n  source TEXT NOT NULL,\n  account_id BIGINT,\n  category_id BIGINT,\n  from_account_id BIGINT,\n  to_account_id BIGINT,\n  flow_kind TEXT NOT NULL DEFAULT 'normal',\n  counterparty TEXT,\n    debt_action TEXT,\n    debt_id BIGINT,\n    debt_payment_id BIGINT,\n    original_amount NUMERIC,\n    original_currency TEXT,\n    exchange_rate NUMERIC,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n  )",
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS account_id BIGINT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS category_id BIGINT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS from_account_id BIGINT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS to_account_id BIGINT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS to_amount NUMERIC',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS to_currency TEXT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS fx_rate NUMERIC',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS fx_rate_text TEXT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS fx_rate_source TEXT',
    "ALTER TABLE transactions ADD COLUMN IF NOT EXISTS flow_kind TEXT NOT NULL DEFAULT 'normal'",
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS counterparty TEXT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS debt_action TEXT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS debt_id BIGINT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS debt_payment_id BIGINT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS original_amount NUMERIC',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS original_currency TEXT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS category_name_snapshot TEXT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS transfer_subtype TEXT',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS family_id BIGINT NULL REFERENCES families (id)',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT NULL REFERENCES users (tg_user_id)',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_by_user_id BIGINT NULL REFERENCES users (tg_user_id)',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS deleted_by_user_id BIGINT NULL REFERENCES users (tg_user_id)',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ NULL',
    'ALTER TABLE transactions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT false',
    "CREATE TABLE IF NOT EXISTS ai_transaction_drafts (\n  id BIGSERIAL PRIMARY KEY,\n  tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  source TEXT NOT NULL,\n  telegram_file_unique_id TEXT NOT NULL,\n  telegram_file_id TEXT,\n  telegram_message_id BIGINT,\n  status TEXT NOT NULL DEFAULT 'pending',\n  transaction_date DATE,\n  tx_type TEXT,\n  amount NUMERIC(18,2),\n  currency TEXT,\n  account_id BIGINT,\n  category_id BIGINT,\n  comment TEXT,\n  confidence NUMERIC(5,4),\n  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  confirmed_at TIMESTAMPTZ,\n  cancelled_at TIMESTAMPTZ\n)",
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS telegram_file_id TEXT',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS telegram_message_id BIGINT',
    "ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending'",
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS transaction_date DATE',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS tx_type TEXT',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS amount NUMERIC(18,2)',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS currency TEXT',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS account_id BIGINT',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS category_id BIGINT',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS comment TEXT',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS confidence NUMERIC(5,4)',
    "ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb",
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ',
    'ALTER TABLE ai_transaction_drafts ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ',
    'CREATE UNIQUE INDEX IF NOT EXISTS ux_ai_transaction_drafts_media ON ai_transaction_drafts (tg_user_id, source, telegram_file_unique_id)',
    'CREATE INDEX IF NOT EXISTS idx_ai_transaction_drafts_status ON ai_transaction_drafts (tg_user_id, status)',
    'CREATE TABLE IF NOT EXISTS saving_prompt_settings (\n  id BIGSERIAL PRIMARY KEY,\n  tg_user_id BIGINT NOT NULL UNIQUE REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  enabled BOOLEAN NOT NULL DEFAULT true,\n  default_percent NUMERIC(5,2) NOT NULL DEFAULT 10,\n  secondary_percent NUMERIC(5,2) DEFAULT 5,\n  default_target_account_id BIGINT,\n  ask_after_income BOOLEAN NOT NULL DEFAULT true,\n  ask_only_for_salary BOOLEAN NOT NULL DEFAULT false,\n  min_income_amount NUMERIC(18,2),\n  reminder_enabled BOOLEAN NOT NULL DEFAULT true,\n  default_reminder_delay TEXT,\n  playful_tone_enabled BOOLEAN NOT NULL DEFAULT true,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)',
    "CREATE TABLE IF NOT EXISTS pending_saving_tasks (\n  id BIGSERIAL PRIMARY KEY,\n  tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  income_transaction_id BIGINT,\n  source_account_id BIGINT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,\n  target_account_id BIGINT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,\n  amount NUMERIC(18,2) NOT NULL,\n  currency TEXT NOT NULL,\n  percent_from_income NUMERIC(5,2),\n  income_amount NUMERIC(18,2),\n  status TEXT NOT NULL DEFAULT 'pending',\n  remind_at TIMESTAMPTZ,\n  reminded_at TIMESTAMPTZ,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  completed_at TIMESTAMPTZ,\n  cancelled_at TIMESTAMPTZ\n)",
    'CREATE INDEX IF NOT EXISTS idx_pending_saving_tasks_due ON pending_saving_tasks (status, remind_at)',
    "CREATE TABLE IF NOT EXISTS daily_expense_reminder_settings (\n  id BIGSERIAL PRIMARY KEY,\n  tg_user_id BIGINT NOT NULL UNIQUE REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  mode TEXT NOT NULL DEFAULT 'daily',\n  reminder_hour INT NOT NULL DEFAULT 21,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)",
    'CREATE TABLE IF NOT EXISTS daily_expense_day_statuses (\n  id BIGSERIAL PRIMARY KEY,\n  tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n  day DATE NOT NULL,\n  reminder_sent_at TIMESTAMPTZ NULL,\n  sent_copy_key TEXT,\n  no_expenses_confirmed_at TIMESTAMPTZ NULL,\n  expense_recorded_at TIMESTAMPTZ NULL,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n  UNIQUE (tg_user_id, day)\n)',
    'CREATE INDEX IF NOT EXISTS idx_daily_expense_day_statuses_day ON daily_expense_day_statuses (day, tg_user_id)',
    "CREATE TABLE IF NOT EXISTS debts (\n    id BIGSERIAL PRIMARY KEY,\n    tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n    family_id BIGINT NULL REFERENCES families (id) ON DELETE SET NULL,\n    counterparty_name TEXT NOT NULL,\n    direction TEXT NOT NULL,\n    initial_amount NUMERIC(18,2) NOT NULL,\n    paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0,\n    remaining_amount NUMERIC(18,2) NOT NULL DEFAULT 0,\n    currency TEXT NOT NULL,\n    account_id BIGINT,\n    status TEXT NOT NULL DEFAULT 'active',\n    due_date DATE,\n    comment TEXT,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n    closed_at TIMESTAMPTZ\n)",
    "ALTER TABLE debts ADD COLUMN IF NOT EXISTS counterparty_name TEXT NOT NULL DEFAULT ''",
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS family_id BIGINT REFERENCES families (id) ON DELETE SET NULL',
    "ALTER TABLE debts ADD COLUMN IF NOT EXISTS direction TEXT NOT NULL DEFAULT 'receivable'",
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS initial_amount NUMERIC(18,2) NOT NULL DEFAULT 0',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC(18,2) NOT NULL DEFAULT 0',
    "ALTER TABLE debts ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'UAH'",
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS account_id BIGINT',
    'ALTER TABLE debts ALTER COLUMN account_id DROP NOT NULL',
    "ALTER TABLE debts ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active'",
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS due_date DATE',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS comment TEXT',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS borrower_user_id BIGINT REFERENCES users (tg_user_id) ON DELETE SET NULL',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS borrower_confirmed_at TIMESTAMPTZ',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN NOT NULL DEFAULT false',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS reminder_frequency TEXT',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS next_reminder_at TIMESTAMPTZ',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS last_reminder_at TIMESTAMPTZ',
    'ALTER TABLE debts ADD COLUMN IF NOT EXISTS reminder_delivery_error TEXT',
    'CREATE TABLE IF NOT EXISTS debt_payments (\n    id BIGSERIAL PRIMARY KEY,\n    tg_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n    family_id BIGINT NULL REFERENCES families (id) ON DELETE SET NULL,\n    debt_id BIGINT NOT NULL REFERENCES debts (id) ON DELETE CASCADE,\n    amount NUMERIC(18,2) NOT NULL,\n    currency TEXT NOT NULL,\n    account_id BIGINT,\n    payment_date DATE NOT NULL,\n    comment TEXT,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n)',
    'ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS amount NUMERIC(18,2) NOT NULL DEFAULT 0',
    'ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS family_id BIGINT REFERENCES families (id) ON DELETE SET NULL',
    "ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'UAH'",
    'ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS account_id BIGINT',
    'ALTER TABLE debt_payments ALTER COLUMN account_id DROP NOT NULL',
    'ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS payment_date DATE',
    'ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS comment TEXT',
    "CREATE TABLE IF NOT EXISTS debt_invites (\n    id BIGSERIAL PRIMARY KEY,\n    debt_id BIGINT NOT NULL REFERENCES debts (id) ON DELETE CASCADE,\n    token TEXT NOT NULL UNIQUE,\n    status TEXT NOT NULL DEFAULT 'pending',\n    created_by_user_id BIGINT NOT NULL REFERENCES users (tg_user_id) ON DELETE CASCADE,\n    used_by_user_id BIGINT NULL REFERENCES users (tg_user_id) ON DELETE SET NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n    used_at TIMESTAMPTZ NULL,\n    expires_at TIMESTAMPTZ NULL\n)",
    'ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS debt_id BIGINT REFERENCES debts (id) ON DELETE CASCADE',
    'ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS token TEXT',
    "ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending'",
    'ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT REFERENCES users (tg_user_id) ON DELETE CASCADE',
    'ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS used_by_user_id BIGINT REFERENCES users (tg_user_id) ON DELETE SET NULL',
    'ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now()',
    'ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS used_at TIMESTAMPTZ',
    'ALTER TABLE debt_invites ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ',
    'CREATE UNIQUE INDEX IF NOT EXISTS idx_debt_invites_token ON debt_invites (token)',
    'CREATE INDEX IF NOT EXISTS idx_debt_invites_debt_pending ON debt_invites (debt_id, status)',
    'CREATE INDEX IF NOT EXISTS idx_debts_family_status ON debts (family_id, status)',
    'CREATE INDEX IF NOT EXISTS idx_debt_payments_family_debt ON debt_payments (family_id, debt_id)',
)
