# Generated by Django 5.1.15 on 2026-05-01 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_pushtopic_tag_useradminstate_admin_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=32)),
                ('category', models.CharField(choices=[('payment', 'Payment'), ('subscription', 'Subscription'), ('onboarding', 'Onboarding'), ('bug', 'Bug'), ('question', 'Question'), ('other', 'Other')], default='other', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=32)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='telegram_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='support_cases', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Support Case',
                'verbose_name_plural': 'Support Cases',
                'db_table': 'support_cases',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], max_length=32)),
                ('text', models.TextField()),
                ('attachment', models.CharField(blank=True, default='', max_length=512)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportcase')),
                ('sender_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'db_table': 'support_messages',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
