# Generated by Codex on 2026-05-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_plan_payment_admin_comment_payment_confirmed_by_and_more"),
        ("users", "0004_useradminstate_test_tools_and_debug"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="action_url",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[("legacy", "Legacy"), ("bind", "Bind"), ("renewal", "Renewal"), ("retry", "Retry")],
                default="legacy",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="grace_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="next_charge_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="monobank", max_length=64)),
                ("wallet_id", models.CharField(max_length=255, unique=True)),
                ("card_token", models.CharField(blank=True, default="", max_length=512)),
                ("masked_pan", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("action_required", "Action required"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("missing_token", "Missing token"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("auto_renew_enabled", models.BooleanField(default=True)),
                ("last_charge_status", models.CharField(blank=True, default="", max_length=64)),
                ("last_failure_reason", models.TextField(blank=True, default="")),
                ("last_action_url", models.CharField(blank=True, default="", max_length=1024)),
                ("last_bound_at", models.DateTimeField(blank=True, null=True)),
                ("last_charge_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="telegram_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_profile",
                        to="users.telegramuser",
                    ),
                ),
            ],
            options={
                "db_table": "billing_profiles",
                "verbose_name": "Billing profile",
                "verbose_name_plural": "Billing profiles",
            },
        ),
    ]
