from django.urls import path

from miniapp import account_deletion_views, funnel_views, views


urlpatterns = [
    path("", views.index, name="index"),
    path("operator/", views.operator_index, name="operator-index"),
    path("browser-login/<str:token>/", views.browser_login_handoff, name="browser-login-handoff"),
    path("api/browser-login/<str:token>/", views.browser_login, name="browser-login-api"),
    path("login/<str:token>/", views.browser_login, name="browser-login"),
    path("family/join/<str:token>/", views.family_join, name="family-join"),
    path("manifest.webmanifest", views.manifest, name="manifest"),
    path("sw.js", views.service_worker, name="service-worker"),
    path("auth/telegram/start", views.telegram_oidc_start, name="telegram-oidc-start"),
    path("auth/telegram/callback", views.telegram_oidc_callback, name="telegram-oidc-callback"),
    path("api/auth/telegram", views.auth_telegram, name="auth-telegram"),
    path("api/auth/dev", views.auth_dev, name="auth-dev"),
    path("api/auth/logout", views.auth_logout, name="auth-logout"),
    path("api/funnel/session", funnel_views.funnel_session, name="funnel-session"),
    path("api/funnel/event", funnel_views.funnel_event, name="funnel-event"),
    path("api/funnel/billing-consent", funnel_views.billing_consent, name="funnel-billing-consent"),
    path("api/profile", views.profile, name="profile"),
    path("api/operator/bootstrap", views.operator_bootstrap, name="operator-bootstrap"),
    path("api/operator/users/<int:tg_user_id>/", views.operator_user_detail, name="operator-user-detail"),
    path("api/operator/users/<int:tg_user_id>/status", views.operator_user_status, name="operator-user-status"),
    path("api/operator/users/<int:tg_user_id>/actions", views.operator_user_action, name="operator-user-action"),
    path("api/onboarding", views.onboarding, name="onboarding"),
    path("api/onboarding/draft", views.onboarding_draft, name="onboarding-draft"),
    path("api/onboarding/confirm", views.onboarding_confirm, name="onboarding-confirm"),
    path("api/settings", views.settings_options, name="settings-options"),
    path("api/install-nudge", views.install_nudge_status, name="install-nudge-status"),
    path("api/install-nudge/event", views.install_nudge_event, name="install-nudge-event"),
    path("api/trial-recovery/event", views.trial_recovery_event, name="trial-recovery-event"),
    path("api/settings/profile", views.settings_profile, name="settings-profile"),
    path("api/settings/reminder", views.settings_reminder, name="settings-reminder"),
    path("api/settings/savings", views.settings_savings, name="settings-savings"),
    path(
        "api/account-deletion",
        account_deletion_views.account_deletion_preflight,
        name="account-deletion-preflight",
    ),
    path(
        "api/account-deletion/confirm",
        account_deletion_views.account_deletion_confirm,
        name="account-deletion-confirm",
    ),
    path("api/notifications", views.notification_status, name="notification-status"),
    path("api/notifications/subscribe", views.notification_subscribe, name="notification-subscribe"),
    path("api/notifications/unsubscribe", views.notification_unsubscribe, name="notification-unsubscribe"),
    path("api/notifications/read", views.notification_read, name="notification-read"),
    path("api/notifications/preferences", views.notification_preferences, name="notification-preferences"),
    path("api/notifications/test", views.notification_test, name="notification-test"),
    path("api/saving-tasks", views.saving_tasks, name="saving-tasks"),
    path("api/saving-tasks/draft", views.saving_task_draft, name="saving-task-draft"),
    path("api/saving-tasks/confirm", views.saving_task_confirm, name="saving-task-confirm"),
    path("api/saving-tasks/cancel", views.saving_task_cancel_draft, name="saving-task-cancel"),
    path("api/settings/billing", views.billing_action, name="billing-action"),
    path("api/family", views.family_overview, name="family-overview"),
    path("api/family/create/draft", views.family_create_draft, name="family-create-draft"),
    path("api/family/create/confirm", views.family_create_confirm, name="family-create-confirm"),
    path("api/family/invite/create", views.family_invite_create, name="family-invite-create"),
    path("api/family/invite/accept", views.family_invite_accept, name="family-invite-accept"),
    path("api/family/invite/revoke", views.family_invite_revoke, name="family-invite-revoke"),
    path("api/family/member/remove", views.family_member_remove, name="family-member-remove"),
    path("api/family/leave", views.family_leave, name="family-leave"),
    path("api/help", views.help_center, name="help-center"),
    path("api/ai-text/parse", views.ai_text_parse, name="ai-text-parse"),
    path("api/ai-voice/parse", views.ai_voice_parse, name="ai-voice-parse"),
    path("api/ai-image/parse", views.ai_image_parse, name="ai-image-parse"),
    path("api/ai-image/batch", views.ai_image_batch, name="ai-image-batch"),
    path("api/ai-image/batch/item", views.ai_image_batch_item, name="ai-image-batch-item"),
    path("api/transactions/options", views.transaction_options, name="transaction-options"),
    path("api/transactions/draft", views.transaction_draft, name="transaction-draft"),
    path("api/transactions/confirm", views.transaction_confirm, name="transaction-confirm"),
    path("api/transactions/cancel", views.transaction_cancel, name="transaction-cancel"),
    path("api/billing-expense/options", views.billing_expense_options, name="billing-expense-options"),
    path("api/billing-expense/draft", views.billing_expense_draft, name="billing-expense-draft"),
    path("api/billing-expense/confirm", views.billing_expense_confirm, name="billing-expense-confirm"),
    path("api/billing-expense/cancel", views.billing_expense_cancel, name="billing-expense-cancel"),
    path("api/accounts/options", views.account_options, name="account-options"),
    path("api/accounts/draft", views.account_draft, name="account-draft"),
    path("api/accounts/confirm", views.account_confirm, name="account-confirm"),
    path("api/accounts/cancel", views.account_cancel, name="account-cancel"),
    path("api/transfers/options", views.transfer_options, name="transfer-options"),
    path("api/transfers/draft", views.transfer_draft, name="transfer-draft"),
    path("api/transfers/confirm", views.transfer_confirm, name="transfer-confirm"),
    path("api/transfers/cancel", views.transfer_cancel, name="transfer-cancel"),
    path("api/debts/options", views.debt_options, name="debt-options"),
    path("api/debts/draft", views.debt_draft, name="debt-draft"),
    path("api/debts/confirm", views.debt_confirm, name="debt-confirm"),
    path("api/debts/cancel", views.debt_cancel, name="debt-cancel"),
    path("api/bootstrap", views.bootstrap, name="bootstrap"),
    path("api/flow", views.flow, name="flow"),
    path("api/categories", views.categories, name="categories"),
    path("api/category-catalog", views.category_catalog, name="category-catalog"),
    path("api/activity", views.activity, name="activity"),
    path("api/history", views.history, name="history"),
    path("api/history/edit/draft", views.history_edit_draft, name="history-edit-draft"),
    path("api/history/edit/confirm", views.history_edit_confirm, name="history-edit-confirm"),
    path("api/history/edit/cancel", views.history_edit_cancel, name="history-edit-cancel"),
    path("api/history/void/draft", views.history_void_draft, name="history-void-draft"),
    path("api/history/void/confirm", views.history_void_confirm, name="history-void-confirm"),
    path("api/history/void/cancel", views.history_void_cancel, name="history-void-cancel"),
    path("api/export.xlsx", views.export_xlsx, name="export-xlsx"),
    path("api/export.csv", views.export_csv, name="export-csv"),
    path("api/accounts", views.accounts, name="accounts"),
    path("api/credit-cards", views.credit_cards, name="credit-cards"),
    path("api/debts", views.debts, name="debts"),
    path("api/goals", views.goals, name="goals"),
    path("api/investments", views.investments, name="investments"),
]
