from __future__ import annotations

from copy import deepcopy


DEFAULT_EXPENSE_CATEGORY_TYPE = "expense"
DEFAULT_EXPENSE_FALLBACK_SLUG = "other"

DEFAULT_EXPENSE_CATEGORIES = [
    {
        "name": "Інше",
        "slug": "other",
        "sort_order": 10,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [],
    },
    {
        "name": "Продукти",
        "slug": "groceries",
        "sort_order": 20,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "супермаркет",
            "market",
            "grocery",
            "groceries",
            "migros",
            "bim",
            "a101",
            "sok",
            "şok",
        ],
    },
    {
        "name": "Кафе, ресторани, доставка",
        "slug": "cafes_restaurants_delivery",
        "sort_order": 30,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "cafe",
            "restaurant",
            "restoran",
            "glovo",
            "bolt food",
            "yemeksepeti",
            "кава",
            "ресторан",
            "доставка їжі",
        ],
    },
    {
        "name": "Оренда житла",
        "slug": "rent",
        "sort_order": 40,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "rent",
            "kira",
            "оренда",
            "аренда",
            "квартира",
            "landlord",
        ],
    },
    {
        "name": "Комунальні платежі",
        "slug": "utilities",
        "sort_order": 50,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "utilities",
            "fatura",
            "electricity",
            "water",
            "gas",
            "комуналка",
            "коммуналка",
            "світло",
            "вода",
            "газ",
            "опалення",
            "квартплата",
            "осбб",
            "aidat",
        ],
    },
    {
        "name": "Дім і побут",
        "slug": "home_household",
        "sort_order": 60,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "побут",
            "household",
            "home",
            "ikea",
            "ремонт",
            "посуд",
            "меблі",
            "хімія",
        ],
    },
    {
        "name": "Транспорт",
        "slug": "transport",
        "sort_order": 70,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "metro",
            "автобус",
            "bus",
            "tram",
            "train",
            "fuel",
            "бензин",
            "пальне",
            "parking",
            "паркування",
        ],
    },
    {
        "name": "Таксі",
        "slug": "taxi",
        "sort_order": 80,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "taxi",
            "uber",
            "bolt",
            "bitaksi",
            "uklon",
        ],
    },
    {
        "name": "Зв'язок та інтернет",
        "slug": "telecom_internet",
        "sort_order": 90,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "internet",
            "mobile",
            "phone",
            "vodafone",
            "kyivstar",
            "lifecell",
            "turkcell",
            "turk telekom",
            "Türk Telekom",
        ],
    },
    {
        "name": "Здоров'я",
        "slug": "health",
        "sort_order": 100,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "pharmacy",
            "eczane",
            "eczanesi",
            "аптека",
            "doctor",
            "лікар",
            "clinic",
            "hospital",
            "стоматолог",
            "аналізи",
        ],
    },
    {
        "name": "Одяг і взуття",
        "slug": "clothes_shoes",
        "sort_order": 110,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "clothes",
            "clothing",
            "shoes",
            "sneakers",
            "zara",
            "hm",
            "lc waikiki",
            "defacto",
        ],
    },
    {
        "name": "Краса та догляд",
        "slug": "beauty_care",
        "sort_order": 120,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "barber",
            "barbershop",
            "salon",
            "косметика",
            "манікюр",
            "стрижка",
            "догляд",
        ],
    },
    {
        "name": "Підписки та сервіси",
        "slug": "subscriptions_services",
        "sort_order": 130,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "subscription",
            "apple",
            "apple.com/bill",
            "app store",
            "google",
            "icloud",
            "itunes",
            "netflix",
            "spotify",
            "youtube",
            "chatgpt",
            "openai",
            "hosting",
            "domain",
        ],
    },
    {
        "name": "Розваги та відпочинок",
        "slug": "entertainment_leisure",
        "sort_order": 140,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "cinema",
            "кіно",
            "games",
            "steam",
            "concert",
            "gym",
            "спорт",
            "хобі",
            "подорож",
            "відпочинок",
        ],
    },
    {
        "name": "Подарунки та донати",
        "slug": "gifts_donations",
        "sort_order": 150,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "gift",
            "donation",
            "donate",
            "подарунок",
            "донат",
            "благодійність",
            "збір",
        ],
    },
]

DEFAULT_EXPENSE_CATEGORY_SLUGS = tuple(category["slug"] for category in DEFAULT_EXPENSE_CATEGORIES)
DEFAULT_EXPENSE_CATEGORY_BY_SLUG = {category["slug"]: category for category in DEFAULT_EXPENSE_CATEGORIES}
DEFAULT_EXPENSE_CATEGORY_NAME_BY_SLUG = {
    category["slug"]: category["name"] for category in DEFAULT_EXPENSE_CATEGORIES
}


def get_default_expense_categories() -> list[dict[str, object]]:
    return deepcopy(DEFAULT_EXPENSE_CATEGORIES)
