# Generated by Django 5.1.15 on 2026-05-01 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Push Topic',
                'verbose_name_plural': 'Push Topics',
                'db_table': 'push_topics',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'user_tags',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='useradminstate',
            name='admin_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='useradminstate',
            name='blocked_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradminstate',
            name='can_receive_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useradminstate',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='useradminstate',
            name='source',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='UserPushTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='users.pushtopic')),
                ('user', models.ForeignKey(db_column='telegram_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='push_topic_settings', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'User Push Topic',
                'verbose_name_plural': 'User Push Topics',
                'db_table': 'user_push_topic_links',
                'ordering': ('topic__name',),
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_tags', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='users.tag')),
                ('user', models.ForeignKey(db_column='telegram_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'User Tag',
                'verbose_name_plural': 'User Tags',
                'db_table': 'user_tag_links',
                'ordering': ('tag__name',),
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
