from __future__ import annotations

from copy import deepcopy


DEFAULT_EXPENSE_CATEGORY_TYPE = "expense"
DEFAULT_EXPENSE_FALLBACK_SLUG = "other"

# Keep a local copy inside admin_service so Django admin/worker/beat do not
# depend on the bot package being present in the image.
DEFAULT_EXPENSE_CATEGORIES = [
    {
        "name": "Р†РЅС€Рµ",
        "slug": "other",
        "sort_order": 10,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [],
    },
    {
        "name": "РџСЂРѕРґСѓРєС‚Рё",
        "slug": "groceries",
        "sort_order": 20,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "СЃСѓРїРµСЂРјР°СЂРєРµС‚",
            "market",
            "grocery",
            "groceries",
            "migros",
            "bim",
            "a101",
            "sok",
            "Еџok",
        ],
    },
    {
        "name": "РљР°С„Рµ, СЂРµСЃС‚РѕСЂР°РЅРё, РґРѕСЃС‚Р°РІРєР°",
        "slug": "cafes_restaurants_delivery",
        "sort_order": 30,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "cafe",
            "restaurant",
            "restoran",
            "glovo",
            "bolt food",
            "yemeksepeti",
            "РєР°РІР°",
            "СЂРµСЃС‚РѕСЂР°РЅ",
            "РґРѕСЃС‚Р°РІРєР° С—Р¶С–",
        ],
    },
    {
        "name": "РћСЂРµРЅРґР° Р¶РёС‚Р»Р°",
        "slug": "rent",
        "sort_order": 40,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "rent",
            "kira",
            "РѕСЂРµРЅРґР°",
            "Р°СЂРµРЅРґР°",
            "РєРІР°СЂС‚РёСЂР°",
            "landlord",
        ],
    },
    {
        "name": "РљРѕРјСѓРЅР°Р»СЊРЅС– РїР»Р°С‚РµР¶С–",
        "slug": "utilities",
        "sort_order": 50,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "utilities",
            "fatura",
            "electricity",
            "water",
            "gas",
            "СЃРІС–С‚Р»Рѕ",
            "РІРѕРґР°",
            "РіР°Р·",
            "РѕРїР°Р»РµРЅРЅСЏ",
            "РєРІР°СЂС‚РїР»Р°С‚Р°",
            "РѕСЃР±Р±",
            "aidat",
        ],
    },
    {
        "name": "Р”С–Рј С– РїРѕР±СѓС‚",
        "slug": "home_household",
        "sort_order": 60,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "РїРѕР±СѓС‚",
            "household",
            "home",
            "ikea",
            "СЂРµРјРѕРЅС‚",
            "РїРѕСЃСѓРґ",
            "РјРµР±Р»С–",
            "С…С–РјС–СЏ",
        ],
    },
    {
        "name": "РўСЂР°РЅСЃРїРѕСЂС‚",
        "slug": "transport",
        "sort_order": 70,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "metro",
            "Р°РІС‚РѕР±СѓСЃ",
            "bus",
            "tram",
            "train",
            "fuel",
            "Р±РµРЅР·РёРЅ",
            "РїР°Р»СЊРЅРµ",
            "parking",
            "РїР°СЂРєСѓРІР°РЅРЅСЏ",
        ],
    },
    {
        "name": "РўР°РєСЃС–",
        "slug": "taxi",
        "sort_order": 80,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "taxi",
            "uber",
            "bolt",
            "bitaksi",
            "uklon",
        ],
    },
    {
        "name": "Р—РІ'СЏР·РѕРє С‚Р° С–РЅС‚РµСЂРЅРµС‚",
        "slug": "telecom_internet",
        "sort_order": 90,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "internet",
            "mobile",
            "phone",
            "vodafone",
            "kyivstar",
            "lifecell",
            "turkcell",
            "turk telekom",
            "TГјrk Telekom",
        ],
    },
    {
        "name": "Р—РґРѕСЂРѕРІ'СЏ",
        "slug": "health",
        "sort_order": 100,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "pharmacy",
            "Р°РїС‚РµРєР°",
            "doctor",
            "Р»С–РєР°СЂ",
            "clinic",
            "hospital",
            "СЃС‚РѕРјР°С‚РѕР»РѕРі",
            "Р°РЅР°Р»С–Р·Рё",
        ],
    },
    {
        "name": "РћРґСЏРі С– РІР·СѓС‚С‚СЏ",
        "slug": "clothes_shoes",
        "sort_order": 110,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "clothes",
            "clothing",
            "shoes",
            "sneakers",
            "zara",
            "hm",
            "lc waikiki",
            "defacto",
        ],
    },
    {
        "name": "РљСЂР°СЃР° С‚Р° РґРѕРіР»СЏРґ",
        "slug": "beauty_care",
        "sort_order": 120,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "barber",
            "barbershop",
            "salon",
            "РєРѕСЃРјРµС‚РёРєР°",
            "РјР°РЅС–РєСЋСЂ",
            "СЃС‚СЂРёР¶РєР°",
            "РґРѕРіР»СЏРґ",
        ],
    },
    {
        "name": "РџС–РґРїРёСЃРєРё С‚Р° СЃРµСЂРІС–СЃРё",
        "slug": "subscriptions_services",
        "sort_order": 130,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "subscription",
            "apple",
            "google",
            "netflix",
            "spotify",
            "youtube",
            "chatgpt",
            "openai",
            "hosting",
            "domain",
        ],
    },
    {
        "name": "Р РѕР·РІР°РіРё С‚Р° РІС–РґРїРѕС‡РёРЅРѕРє",
        "slug": "entertainment_leisure",
        "sort_order": 140,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "cinema",
            "РєС–РЅРѕ",
            "games",
            "steam",
            "concert",
            "gym",
            "СЃРїРѕСЂС‚",
            "С…РѕР±С–",
            "РїРѕРґРѕСЂРѕР¶",
            "РІС–РґРїРѕС‡РёРЅРѕРє",
        ],
    },
    {
        "name": "РџРѕРґР°СЂСѓРЅРєРё С‚Р° РґРѕРЅР°С‚Рё",
        "slug": "gifts_donations",
        "sort_order": 150,
        "is_default": True,
        "type": DEFAULT_EXPENSE_CATEGORY_TYPE,
        "aliases": [
            "gift",
            "donation",
            "donate",
            "РїРѕРґР°СЂСѓРЅРѕРє",
            "РґРѕРЅР°С‚",
            "Р±Р»Р°РіРѕРґС–Р№РЅС–СЃС‚СЊ",
            "Р·Р±С–СЂ",
        ],
    },
]

DEFAULT_EXPENSE_CATEGORY_SLUGS = tuple(category["slug"] for category in DEFAULT_EXPENSE_CATEGORIES)
DEFAULT_EXPENSE_CATEGORY_BY_SLUG = {
    category["slug"]: category for category in DEFAULT_EXPENSE_CATEGORIES
}
DEFAULT_EXPENSE_CATEGORY_NAME_BY_SLUG = {
    category["slug"]: category["name"] for category in DEFAULT_EXPENSE_CATEGORIES
}


def get_default_expense_categories() -> list[dict[str, object]]:
    return deepcopy(DEFAULT_EXPENSE_CATEGORIES)
