# Generated by Django 5.1.15 on 2026-05-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
        ('users', '0002_pushtopic_tag_useradminstate_admin_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('tag', 'Tag'), ('source', 'Source')], default='system', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'db_table': 'segments',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='adminmessagelog',
            name='buttons_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminmessagelog',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='button_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='manual_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='target_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='users.tag'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='target_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='users.pushtopic'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='target_type',
            field=models.CharField(choices=[('all', 'All'), ('segment', 'Segment'), ('tag', 'Tag'), ('manual_users', 'Manual Users'), ('push_topic', 'Push Topic')], default='all', max_length=32),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminmessagelog',
            name='telegram_user',
            field=models.ForeignKey(blank=True, db_column='telegram_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='users.telegramuser'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('completed', 'Completed (Legacy)'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='target_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='broadcasts.segment'),
        ),
    ]
